name: Veracode scan

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore --ignore-failed-sources

    - name: Publish solution
      run: dotnet publish src/Laserfiche.Api.Client.Core.csproj --no-restore

    - name: Veracode Upload And Scan (Static Application Security Testing)
      uses: veracode/veracode-uploadandscan-action@0.2.6
      with:
        appname: 'lf-api-client-core-dotnet'
        createprofile: true
        filepath: 'src/bin/Debug/netstandard2.0'
        vid: '${{ secrets.VERACODE_API_ID }}'
        vkey: '${{ secrets.VERACODE_API_KEY }}'

    - name: Run Veracode Software Composition Analysis (SCA)
      env:
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      run: curl --silent --show-error --location https://download.sourceclear.com/ci.sh | sh -s -- scan ./ --update-advisor --allow-dirty

